/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lenguaje;

import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *  @author Saul Cervantes Candia - 177927
 *          Ana Karen Cuenca Esquivel - 177932
 */
public class Animacion extends javax.swing.JFrame {
    int  pos = 0, estado = 0, cont = 0, estIni = 0, dire = 0;
    String COLOR = "\u001B[36m";
    String RED = "\u001B[31m";
    String GREEN = "\u001B[32m";
    String X = "\u001B[33m";
    String RESET = "\u001B[0m";
    String ant, nue;
    public Animacion() {
        initComponents();
        this.setTitle("Palíndromo");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfPalabra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnComprobar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese la palabra");

        btnComprobar.setText("Comprobar");
        btnComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(112, 112, 112)
                        .addComponent(tfPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnComprobar)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(btnComprobar)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarActionPerformed
        String pal = tfPalabra.getText();
        int x = pal.length();
        System.out.println("Cantidad de letras: "+x);
        System.out.println("Palabra : "+pal);
        estIni = 0;
        estado = 0;
        pos = 0;
        int contador = 0;
        if(x != 0){
            ArrayList<String> letras;
            letras = new ArrayList<String>(Arrays.asList(pal.split("")));
            letras.add("D");
            for (int i = 0; i < letras.size()-1; i++) {
                if(letras.get(i).equals("a") || letras.get(i).equals("b")){
                    contador++;
                }else{
                    JOptionPane.showMessageDialog(this, "Lo siento, solo aceptamos 'a' o 'b'");
                    tfPalabra.setText("");
                    estado = 8;
                    break;
                }
            }
            if(contador == (letras.size()-1)){
                System.out.println(letras+"\tPosicion: "+pos+"\tInicial: "+estIni+"\tFinal: "+estado);
                compPali(letras);
                tfPalabra.setText("");
                System.out.println("\n");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe de ingresar al menos una letra");
        }
    }//GEN-LAST:event_btnComprobarActionPerformed
    
    public void compPali(ArrayList<String> a){
        int x = a.size(), cont2 = 0;
        while(estado != 8){
            estIni = estado;
            System.out.print(COLOR+"Regla "+RESET+"("+estado+","); 
            if(estado == 0){
                regI(a,a.get(pos));
            }else if(estado == 1){
                regE1(a,a.get(pos));
            }else if(estado == 2){
                regE2(a,a.get(pos));
            }else if(estado == 3){
                regE3(a,a.get(pos));
            }else if(estado == 4){
                regE4(a,a.get(pos));
            }else if(estado == 5){
                regE5(a,a.get(pos));
            }else if(estado == 6){
                regE6(a,a.get(pos));
            }else if(estado == 7){
                regE7(a,a.get(pos));
            }
            System.out.print("\t");
            cambio(a);
            System.out.print(RED+"\t Cambio: "+RESET+ant+" - "+nue);
            System.out.println(GREEN+"\tPosicion Actual: "+RESET+pos+COLOR+"\tInicial: "+RESET+estIni+COLOR+"\tFinal: "+RESET+estado+"\n");
            if(cont == 3){
                cont = 0;
                break;
            }
        }
        for (int i = 0; i < x-1; i++) {
            if(a.get(i).equals("L") || a.get(i).equals("B")){
                cont2++;
            }else{
                JOptionPane.showMessageDialog(this, "Lo siento pero no es un palindromo :(");
                tfPalabra.setText("");
                break;
            }
        }
        if(cont2 == x-1){
            JOptionPane.showMessageDialog(this, "Felicidades, usted ingreso un palíndromo :)");
        }
    }
    
    private void regI(ArrayList<String> a, String letra){
        if(letra.equals("a")){
            System.out.print("a)");
            estado = 1;
            ant = a.get(pos);
            a.set(pos, "L");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else if(letra.equals("b")){
            System.out.print("b)");
            estado = 4;
            ant = a.get(pos);
            a.set(pos, "B");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else if(letra.equals("L")){
            System.out.print("L)");
            estado = 7;
            ant = a.get(pos);
            a.set(pos, "L");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else if(letra.equals("B")){
            System.out.print("B)");
            estado = 7;
            ant = a.get(pos);
            a.set(pos, "B");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else if(letra.equals("D")){
            System.out.print("D)");
            estado = 8;
            ant = a.get(pos);
            a.set(pos, "D");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else{
            cont++;
        }
    }
    
    private void regE1(ArrayList<String> a, String letra){
        if(letra.equals("a")){
            System.out.print("a)");
            estado = 1;
            ant = a.get(pos);
            a.set(pos, "a");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else if(letra.equals("b")){
            System.out.print("b)");
            estado = 1;
            ant = a.get(pos);
            a.set(pos, "b");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else if(letra.equals("L")){
            System.out.print("L)");
            estado = 3;
            ant = a.get(pos);
            a.set(pos, "L");
            nue = a.get(pos);
            pos--;
            dire = 0;
        }else if(letra.equals("B")){
            System.out.print("B)");
            estado = 3;
            ant = a.get(pos);
            a.set(pos, "B");
            nue = a.get(pos);
            pos--;
            dire = 0;
        }else if(letra.equals("D")){
            System.out.print("D)");
            estado = 3;
            ant = a.get(pos);
            a.set(pos, "D");
            nue = a.get(pos);
            pos--;
            dire = 0;
        }else{
            cont++;
        }
    }
    
    private void regE2(ArrayList<String> a, String letra){
        if(letra.equals("a")){
            System.out.print("a)");
            estado = 2;
            ant = a.get(pos);
            a.set(pos, "a");
            nue = a.get(pos);
            pos--;
            dire = 0;
        }else if(letra.equals("b")){
            System.out.print("b)");
            estado = 2;
            ant = a.get(pos);
            a.set(pos, "b");
            nue = a.get(pos);
            pos--;
            dire = 0;
        }else if(letra.equals("L")){
            System.out.print("L)");
            estado = 0;
            ant = a.get(pos);
            a.set(pos, "L");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else{
            cont++;
        }
    }

    private void regE3(ArrayList<String> a, String letra){
        if(letra.equals("a")){
            System.out.print("a)");
            estado = 2;
            ant = a.get(pos);
            a.set(pos, "L");
            nue = a.get(pos);
            pos--;
            dire = 0;
        }else if(letra.equals("L")){
            System.out.print("L)");
            estado = 0;
            ant = a.get(pos);
            a.set(pos, "L");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else if(letra.equals("B")){
            System.out.print("B)");
            estado = 0;
            ant = a.get(pos);
            a.set(pos, "B");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else{
            cont++;
        }
    }
    
    private void regE4(ArrayList<String> a, String letra){
        if(letra.equals("a")){
            System.out.print("a)");
            estado = 4;
            ant = a.get(pos);
            a.set(pos, "a");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else if(letra.equals("b")){
            System.out.print("b)");
            estado = 4;
            ant = a.get(pos);
            a.set(pos, "b");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else if(letra.equals("L")){
            System.out.print("L)");
            estado = 6;
            ant = a.get(pos);
            a.set(pos, "L");
            nue = a.get(pos);
            pos--;
            dire = 0;
        }else if(letra.equals("B")){
            System.out.print("B)");
            estado = 6;
            ant = a.get(pos);
            a.set(pos, "B");
            nue = a.get(pos);
            pos--;
            dire = 0;
        }else if(letra.equals("D")){
            System.out.print("D)");
            estado = 6;
            ant = a.get(pos);
            a.set(pos, "D");
            nue = a.get(pos);
            pos--;
            dire = 0;
        }else{
            cont++;
        }
    }
    
    private void regE5(ArrayList<String> a, String letra){
        if(letra.equals("a")){
            System.out.print("a)");
            estado = 5;
            ant = a.get(pos);
            a.set(pos, "a");
            nue = a.get(pos);
            pos--;
            dire = 0;
        }else if(letra.equals("b")){
            System.out.print("b)");
            estado = 5;
            ant = a.get(pos);
            a.set(pos, "b");
            nue = a.get(pos);
            pos--;
            dire = 0;
        }else if(letra.equals("B")){
            System.out.print("B)");
            estado = 0;
            ant = a.get(pos);
            a.set(pos, "B");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else{
            cont++;
        }
    }
    
    private void regE6(ArrayList<String> a, String letra){
        if(letra.equals("b")){
            System.out.print("b)");
            estado = 5;
            ant = a.get(pos);
            a.set(pos, "B");
            nue = a.get(pos);
            pos--;
            dire = 0;
        }else if(letra.equals("L")){
            System.out.print("L)");
            estado = 0;
            ant = a.get(pos);
            a.set(pos, "L");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else if(letra.equals("B")){
            System.out.print("B)");
            estado = 0;
            ant = a.get(pos);
            a.set(pos, "B");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else{
            cont++;
        }
    }
    
    private void regE7(ArrayList<String> a, String letra){
        if(letra.equals("L")){
            System.out.print("L)");
            estado = 7;
            ant = a.get(pos);
            a.set(pos, "L");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else if(letra.equals("B")){
            System.out.print("B)");
            estado = 7;
            ant = a.get(pos);
            a.set(pos, "B");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else if(letra.equals("D")){
            System.out.print("D)");
            estado = 8;
            ant = a.get(pos);
            a.set(pos, "D");
            nue = a.get(pos);
            pos++;
            dire = 1;
        }else{
            cont++;
        }
    }
    
    public void cambio(ArrayList<String> a){
        int x = a.size();
        int aux = pos;
        System.out.print("( ");
        for (int i = 0; i < x; i++) {
            if(dire == 1){
                if(i == (aux-1)){
                    if(estado != 8){
                        if(!(ant.equals(nue))){
                            System.out.print(RED+a.get(i)+RESET+" ");
                            i++;
                            if(i != x){
                                System.out.print(GREEN+a.get(i)+RESET+" ");
                            }
                        }else{
                            System.out.print(a.get(i)+" ");
                            i++;
                            System.out.print(GREEN+a.get(i)+RESET+" ");
                        }
                    }else{
                        System.out.print(a.get(i)+" ");
                    }
                }else{
                    System.out.print(a.get(i)+" ");
                }
            }else{
                if(i == aux){
                    if(!(ant.equals(nue))){
                        System.out.print(GREEN+a.get(i)+RESET+" ");
                        i++;
                        System.out.print(RED+a.get(i)+RESET+" ");
                    }else{
                        System.out.print(GREEN+a.get(i)+RESET+" ");
                        i++;
                        System.out.print(a.get(i)+" ");
                    }
                }else{
                    System.out.print(a.get(i)+" ");
                }
            }
        }
        System.out.print(")");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnComprobar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfPalabra;
    // End of variables declaration//GEN-END:variables
}
